AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/ClientRestaurants.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages.Restaurants
{
    public class ClientRestaurantsModel : PageModel
    {

    }
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class DeleteModel : PageModel
    {
        private readonly IRestaurantData restaurantData;

        public Restaurant Restaurant { get; set; } 

        public DeleteModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = restaurantData.GetById(restaurantId);
            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost(int restaurantId)
        {
            var restaurant = restaurantData.Delete(restaurantId);
            restaurantData.Commit();
            if (restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            TempData["Message"] = $"{restaurant.Name} deleted";
            return RedirectToPage("./List");
        }
    }
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class DetailModel : PageModel
    {
        private readonly IRestaurantData restaurantData;

        public Restaurant Restaurant { get; set; }

        public DetailModel( IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IActionResult OnGet(int restaurantId)
        {

            Restaurant = restaurantData.GetById(restaurantId);

            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }
    }
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData restaurantData;
        private readonly IHtmlHelper htmlHelper;

        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }

        public EditModel(IRestaurantData restaurantData, 
                            IHtmlHelper htmlHelper)
        {
            this.restaurantData = restaurantData;
            this.htmlHelper = htmlHelper;
        }

        public IActionResult OnGet(int? restaurantId)
        {
            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();

            if (restaurantId.HasValue)
            {
                Restaurant = restaurantData.GetById(restaurantId.Value);
            }
            else
            {
                Restaurant = new Restaurant();
            }
            

            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {

            if (!ModelState.IsValid)
            {
                Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();

                return Page();
            }


            if (Restaurant.Id > 0)
            {
                restaurantData.Update(Restaurant);
            }
            else
            {
                restaurantData.Add(Restaurant);
            }
            
            restaurantData.Commit();

            TempData["Message"]= "Restaurant Saved!";

            return RedirectToPage("./Detail", new { restaurantId = Restaurant.Id });

        }

    }
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        private readonly IRestaurantData restaurantData;
        private readonly ILogger<ListModel> logger;

        public string Message { get; set; }
        public IEnumerable<Restaurant> Restaurants { get;set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public ListModel(IConfiguration config, 
                         IRestaurantData restaurantData,
                         ILogger<ListModel> logger)
        {
            this.config = config;
            this.restaurantData = restaurantData;
            this.logger = logger;
        }

        public void OnGet()
        {
            logger.LogError("Executing ListModel");
            Message = config["Message"];
            Restaurants = restaurantData.GetRestaurantsByName(SearchTerm);
        }
    }
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/ViewComponents/RestaurantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class RestaurantCountViewComponent : ViewComponent
    {
        private readonly IRestaurantData restaurantData;

        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IViewComponentResult Invoke()
        {
            var count = restaurantData.GetCountOfRestaurants();
            return View(count);
        }

    }
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/ClientRestaurants.cshtml
@page
@model OdeToFood.Pages.Restaurants.ClientRestaurantsModel
@{
    ViewData["Title"] = "ClientRestaurants";
}

<h1>ClientRestaurants</h1>

<table class="table table-striped table-bordered" id="restaurants">
    <thead>
        <tr>
            <th>name</th>
            <th>location</th>
            <th>cuisine</th>
        </tr>
    </thead>
</table>

@section Scripts{

<environment include="Development">

    <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.js"></script>
    <link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
    
</environment>
    <environment exclude="Development">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css" />
        <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>
    </environment>


    <script>
        $(function () { 

            var cuisines = ["Unknown","Mexican","Italian","Indian"]

            $.ajax("/api/restaurants/", { method: "get" })
                .then(function (response) {
                    $("#restaurants").dataTable({
                        data: response,
                        columns: [
                            { "data": "name" },
                            { "data": "location" },
                            { "data": "cuisine", "render": function (data) { return cuisines[data]; } },

                        ]
                    });
                });
        });
    </script>
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/Delete.cshtml
@page "{restaurantId:int}"
@model OdeToFood.Pages.Restaurants.DeleteModel
@{
    ViewData["Title"] = "Delete";
}


<h2>Delete!</h2>
<div class="alert alert-danger">
    Are you sure you want to delete @Model.Restaurant.Name ?
</div>
<form method="post">
    <button type ="submit" class="btn btn-danger">Yes!</button>
    <a asp-page="List" class="btn btn-info">Cancel</a>
</form>

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/Detail.cshtml
@page "{restaurantId:int}"

@model OdeToFood.Pages.Restaurants.DetailModel
@{
    ViewData["Title"] = "Detail";
}


@if (Model.Message != null)
{
    <div class="alert alert-success">@Model.Message</div>
}

<h2>@Model.Restaurant.Name</h2>
<div>
    Id: @Model.Restaurant.Id
</div>
<div>
    Location: @Model.Restaurant.Location
</div>
<div>
    Cuisine: @Model.Restaurant.Cuisine
</div>


<a asp-page="./List" class="btn btn-default">All Restaurants</a>

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{restaurantId:int?}"
@model OdeToFood.Pages.Restaurants.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Editing @Model.Restaurant.Name</h1>

<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />
    <div class="form-group">
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Location"></label>
        <input asp-for="Restaurant.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurant.Location"></span>

    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Cuisine"></label>
        <select class="form-control" asp-for="Restaurant.Cuisine" asp-items="Model.Cuisines"></select>
        <span class="text-danger" asp-validation-for="Restaurant.Cuisine"></span>

    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts{ 
    <partial name="_ValidationScriptsPartial" />
}

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/List.cshtml
@page
@model ListModel
@{
    ViewData["Title"] = "List";
}

<h1>Restaurants</h1> 

<form method="get">
    <div class="form-group">
        <div class="input-group mb-3">
            <input type="search" class="form-control" asp-for="SearchTerm"/>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</form>

@*<table class="table">
    @foreach (var restaurant in Model.Restaurants)
    {
    <tr>
        <td>@restaurant.Name</td>
        <td>@restaurant.Location</td>
        <td>@restaurant.Cuisine</td>
        <td>
            <a class="btn btn-lg" asp-page="./Detail" asp-route-restaurantId="@restaurant.Id"><i class="fa fa-search-plus"></i></a>
            <a class="btn btn-lg" asp-page="./Edit" asp-route-restaurantId="@restaurant.Id"><i class="fa fa-edit"></i></a>
            <a class="btn btn-lg" asp-page="./Delete" asp-route-restaurantId="@restaurant.Id"><i class="fa fa-trash"></i></a>
        </td>
    </tr>
    }

</table>*@

@foreach (var restaurant in Model.Restaurants)
{
    <partial name="_Summary" model="restaurant" />
}

<a asp-page=".\Edit" class="btn btn-primary">Add New</a>

<div>@Model.Message</div>

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h1>Restaurant was not found</h1>

<a asp-page="./List" class="btn btn-primary"> See All Restaurants</a>

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Restaurants/_Summary.cshtml
@using OdeToFood.Core
@model Restaurant

<div class="col-lg-9">
    <div class="card mb-3">
        <div class="card-header">
            <h3>@Model.Name</h3>
        </div>
        <div class="card-body">
            <span>Location: @Model.Location</span>
            <span>Cuisine: @Model.Cuisine</span>
        </div>
        <div class="card-footer">
            <a class="btn btn-lg" asp-page="./Detail" asp-route-restaurantId="@Model.Id"><i class="fa fa-search-plus"></i></a>
            <a class="btn btn-lg" asp-page="./Edit" asp-route-restaurantId="@Model.Id"><i class="fa fa-edit"></i></a>
            <a class="btn btn-lg" asp-page="./Delete" asp-route-restaurantId="@Model.Id"><i class="fa fa-trash"></i></a>
        </div>
    </div>
</div>

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<div class="well">
    There are @Model restaurants. <a asp-page="/Restaurants/List">See them all!</a>
</div>

AspNetCoreFundamentals/OdeToFood/OdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                            
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <vc:restaurant-count></vc:restaurant-count>
            &copy; 2019 - OdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a>
            <img src="/food.png" />
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/font-awesome/js/all.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
        <script src="~/lib/font-awesome/js/all.min.js"></script>

    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>